### PR TITLE
Add tick options for X & Y axis.

### PR DESCRIPTION
**Pull request by mfollett**
Adds a tickOption field that extends other tick options. This'll allow for things like culling and no multiline.

### CODE REVIEW

**Comment by mfollett** [comment]
This isn't ready yet, but I can't get node_packages to install for some reason, just keeps hanging, so I'm relying on Travis to run the tests.

**Comment by mfollett** [comment]
I didn't touch the styling so I'm not sure why the minified CSS changed. Otherwise, this adds a new field onto xAxis and yAxis (`tickOptions`) that allows for various tick options. One can use this to do things like culling ticks and setting no multiline.

**Comment by mfollett** [comment]
If you want me to revert the styling in this pull request I'd be more than happy to do so.

**Comment by mfollett** [comment]
This is for issue #69.

**Comment by maxklenk** [comment]
Thank you for providing this perfect merge request. I also have no idea why the CSS changed, but that's no problem as fare as I see it was just ordered differently.

**Pull request merged**
